### ISSUE TITLE
Make trimming optional

### ISSUE THREAD

**Issue by csoneson** [csoneson/rnaseqworkflow#10]

**Comment by sorjuela** [comment]
Make STAR, trim and other optional?

**Comment by csoneson** [comment]
This involves making conditional Snakemake rules, where the input files depend on variables set in the config file.

**Comment by khembach** [comment]
Trimming, STAR mapping and DRIMSeq analysis can now be deactivated by setting the corresponding variables in config.yaml to "False". Last commit related to this is 9e5d79d.
