### ISSUE TITLE
Convert statistical analysis scripts into R/markdown templates

### ISSUE THREAD

**Issue by csoneson** [csoneson/rnaseqworkflow#13]
- [x] Provide edgeR and DRIMSeq analysis code as .Rmd files.
- [x] Save figures in png/pdf
- [x] Export results of the analyses

**Comment by sorjuela** [comment]
1.1. Split tximeta to a separate script
1.2. Merge outputs for shiny?

**Comment by csoneson** [comment]
DRIMSeq Rmd added in ed977b85889f9c4f4d9a372c98b19491f8f7885a
