### ISSUE TITLE
Ensembl -> Gencode

### ISSUE THREAD

**Issue by csoneson** [csoneson/rnaseqworkflow#2]
Change the default annotation catalog from Ensembl to Gencode. Avoids the need to merge cDNA and ncRNA fasta files, and ensures that the gtf and fasta file have the same set of transcripts. 

Affects at least the following files:
- `README.md` (instructions for downloading reference files)
- `config.yaml` (remove cdna and ncrna, use only txome)
- `Snakefile` (no need to merge cDNA and ncRNA files)
- `generate_tx2gene.R` (transcript ID format is different)
- `run_dge_edgeR.R` and `run_dtu_drimseq.R` (set `ignoreAfterBar=TRUE` in `tximport` call - alternatively run Salmon indexing with `gencode` flag)

To make things more general (allow as many species as possible), we could allow both Ensembl and Gencode (potentially requiring the user to merge the cDNA and ncRNA files on their own beforehand, if they want to use both). Then, in both cases we would only require an input `txome`, and remove the cDNA/ncRNA merging.

**Comment by sorjuela** [comment]
I think I can do this. Maybe also the tximeta implementation, since there's some crosstalk with this. But for now I will only assign this to myself.

**Comment by csoneson** [comment]
Great. We may want to have a flag that the user can set to tell the workflow whether the reference files are from Ensembl or Gencode (mostly since the transcript IDs should be processed differently).

**Comment by sorjuela** [comment]
you mean something in the config.yaml?

**Comment by csoneson** [comment]
Yes, exactly. And then the value of this flag will affect the workflow in the appropriate places.

**Comment by sorjuela** [comment]
Ok so in my branch I added a new script called "generate_tx2gene_tximeta.R" an it's basically the tximeta version of "generate_tx2gene.R". I pushed it to get some feedback and because I think it works, but I don't know how to put the tximeta package in conda.
Another problem is that the tximeta doesn't return gene symbol, so I have to do something else for that.

**Comment by csoneson** [comment]
A couple of comments relating mostly to the `tximeta` integration:
- I don't think we need the `tx2gene` anymore - this information will be automatically extracted and added by `tximeta`
- I could imagine that in the Salmon index generation rule, there will be an additional step creating the `linkedTxome` with `tximeta`, from the provided fasta and gtf files (so there are two output files from this rule - or maybe it's easier to have an additional rule generating the `linkedTxome`)
- In the `edgeR` and `DRIMSeq` scripts, we should then be able to just do `x<-tximeta(metadata)` to import the abundances and add annotations, and then `y<-summarizeToGene(x)` to get the gene-level data. So no need for the `tx2gene` object. The provided `metadata` needs to be extended with a column `files` for this to work, pointing to the Salmon output files.
- Perhaps we should rename our `ID` column in the metadata file to `names` instead, so that we don't have to rename it later for `tximeta`.

**Comment by sorjuela** [comment]
I added all the things mentioned above. I ended up adding an additional rule to generate the `linkedTxome`, which seemed like the easiest thing. 
A couple of things still missing (to me): 
* Fixing the `prepare_results_for_shiny` script. I removed the tx2gene there, and it seemed fine, but I think there's a matching problem with the `gene` names to generate the `logCPM` plots in `iResViewer`. I'll look into it another day.
* Fixing the `README` to add the new things to be specified in the `config.yaml` (gencode/ensembl, organism, build, release...)
* Implementing `tximeta` in the `DRIMseq` script.
* I still need to do a full run with the `gencode` reference files.

**Comment by csoneson** [comment]
I ran through the analysis, and overall things seem to be working well. There are a couple of things that need to be specified/clarified, in addition to your points above:
- the `edgeR`/`DRIMSeq` rules must depend on the generation of the linkedTxome - otherwise the latter will never be generated
- the `edgeR`/`DRIMSeq` rules must also depend on the actual Salmon index which is generated earlier (the `hash.bin` file) - otherwise the workflow will complain that there is no rule to create `config["salmonindex"]`
- we should specify that both the genome fasta and the gtf must be uncompressed, otherwise STAR will not work
- things work also for Gencode, but we need to handle the different transcript identifiers (separated by | rather than space). Probably the most straightforward way is to invoke Salmon with the `--gencode` flag if the config file specifies that the reference files are from Gencode. Then the downstream things should work with the current code

**Comment by csoneson** [comment]
Also, the `metadata.txt` file should not be in this repo

**Comment by sorjuela** [comment]
Last commit related to this I think was https://github.com/csoneson/rnaseqworkflow/commit/5ce148ed81e9a360d281e96dbf2142bac95aca3f or this one https://github.com/csoneson/rnaseqworkflow/commit/13f1d72d2cae43236838263f9971d1f574036e8d
