### ISSUE TITLE
Software version numbers

### ISSUE THREAD

**Issue by csoneson** [csoneson/rnaseqworkflow#21]
We discussed this, and probably it's best to remove the version numbers from the `environment.yaml` file, so that users will not be stuck with old versions. Any user can always specify the versions they want (to make their own analyses reproducible), and we can provide a list of the versions that we have tested the workflow with. In the Wiki, we can also show how to export an environment file from a specific conda environment.

**Comment by fionarhuang** [comment]
One possibility is to have a git_install file as I sent in the slack to install R packages. In that file, it will check whether  the list packages are already installed in the environment. If not, it will download automatically. Of course, the packages are downloaded from CRAN, Bioconductor or github, so it would be the newest version. If users would like to use a specific R packages version, they could specify it in the environment.yaml file and update the environment. When they run the pipeline, the git_install will check the packages again and install those that are not downloaded yet. This has the advantage that users are free to choose the versions they like and less likely to get the complicated conflict issue. The way we are doing now could work at this moment and fail at another moment. This would be painful for users to figure out how to solve the issue by themselves and probably also difficult for the future maintenance. Also, I guess the R packages in bioconductor or CRAN are more likely to be continously maintained than those in Bioconda. Now, we have the latest R version 3.5.1 in the conda. However, we can't build the environment using it with any R packages, even the popular package, such as ggplot2 or edgeR.

**Comment by csoneson** [comment]
Thinking about this again, perhaps we want to keep the version numbers in the environment file, to represent a setup that has been tested.
