### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by sorjuela** [csoneson/rnaseqworkflow#30]
Use Travis CI?
Test different versions of config.yaml?
Use a predefined output to test, put it in github?

**Comment by csoneson** [comment]
travis is set up in 01f1ed3454e8276f3a525d69752622529733d209. Currently times out while installing the packages.

**Comment by csoneson** [comment]
working in 4aa3bbb2fcf1828ff983e556c5c17927847ea67b (testing `tximeta` and `multiqc` rules+prerequisites)
